name: sayer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Enable to override the white screen in app initialization  
  flutter_native_splash: ^2.4.6  

  # Provide responsive design 
  flutter_screenutil: ^5.9.3

  # Using URL 
  url_launcher: ^6.3.2

  # Localization
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter

  # Multi-select dropdown field
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Load all images inside the images folder
    - assets/showrooms/  

  fonts:
    - family: "Montserrat"
      fonts: 
        - asset: "assets/fonts/Montserrat-Arabic-Regular.ttf"
